spring:
  redis:
    #Redis数据库索引（默认为0）
    database: 2
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: 123456
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 24
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000ms
    #连接超时时间（毫秒）
    timeout: 1000ms


redisson:
  password: 123456
  #redisson单机配置
  single:
    address: 127.0.0.1:6379
  #redisson集群配置
  cluster:
    nodes: 127.0.0.1:6379;

server:
  port: 9098
