server:
  port: 9098

spring:
  redis:
    #Redis数据库索引（默认为0）
    database: 2
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: 123456
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 24
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000ms
    #连接超时时间（毫秒）
    timeout: 1000ms
  #邮件配置
  mail:
    #smtp.qq.com个人邮箱，smtp.exmail.qq.com企业邮箱
    host: smtp.qq.com
    username: 1826378013@qq.com
    password: hjqymdqdzxcedeia123
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
    port: 465

mail:
  receiver: 2668690328@qq.com;

#redisson配置
redisson:
  password: 123456
  #redisson单机配置
  single:
    address: 127.0.0.1:6379
  #redisson集群配置
  cluster:
    nodes: 127.0.0.1:6379;

#异步相关配置
async:
  config:
    corepoolsize: 10
    maxpoolsize: 20
    queuecapacity: 500




