spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: db-user-0
      db-user-0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/local_learn?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 10
        maxWait: 5000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    sharding:
      tables:
        tb_user:
          actual-data-nodes: db-user-0.tb_user_$->{0..1}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: tb_user_$->{user_id % 2}
    props:
      sql:
        show: true

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.philosopherzb.shardingtable.domain  # 注意：对应实体类的路径

server:
  port: 8083
